### ISSUE TITLE
Social media section missing from module 6

### ISSUE THREAD

**Issue by rpa1111** [kbenoit/ITAUR#9]
Hi! I was looking at the following notes: https://github.com/kbenoit/ITAUR   and found that "analyzing social media" is missing from Module 6. I'd love to see this section. Would you be able to fix this link?

![mod 6](https://user-images.githubusercontent.com/8264425/31562549-7ff5eb48-b021-11e7-8b46-dcac264993e4.JPG)

Thanks!
~RA

**Comment by kbenoit** [comment]
Added now as an .R file

**Comment by rpa1111** [comment]
Wonderful! Thanks for adding this!
